version: '3.7'
services:
  db:
    image: postgres
    container_name: oshaller-postgresql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./app:/go/src/app